linters:
  enable-all: true
  disable:
  - depguard
  - execinquery # deprecated since v1.58.0
  - funlen
  - gci
  - gochecknoglobals
  - goconst
  - gofumpt
  - gomnd
  - lll
  - mnd # some magic numbers are acceptable.
  - nlreturn
